version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hyf-soujanya-cron-homework-lamda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fh54iz3nan0g"
s3_prefix = "hyf-soujanya-cron-homework-lamda"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
