AWSTemplateFormatVersion: 2010-09-09
# Transform: AWS::Serverless-2016-10-31
Description: >
  homework-assignment
Resources:
  ScheduledEventLogger:
    # Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that logs the payload of messages sent to an associated SQS queue.
      Runtime: nodejs14.x
      # Handler: scheduled-event-logger.scheduledEventLoggerHandler
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            # Schedule: cron(0 * * * ? *)
      MemorySize: 128
      Timeout: 100
